import React, { useState, useRef, useEffect } from 'react';
import Modal from './Modal';
import Loader from './Loader';
import { generatePresentationContent } from '../services/geminiService';
import { PresentationSlide } from '../types';

interface PresentationGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
}

// Add declarations for the global libraries loaded via script tags
declare var PptxGenJS: any;
declare var jspdf: any;

const PresentationGenerator: React.FC<PresentationGeneratorProps> = ({ isOpen, onClose }) => {
  const [topic, setTopic] = useState('');
  const [slides, setSlides] = useState<PresentationSlide[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isDownloadMenuOpen, setIsDownloadMenuOpen] = useState(false);
  const downloadMenuRef = useRef<HTMLDivElement>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) {
      setError("Please enter a presentation topic.");
      return;
    }
    setIsLoading(true);
    setError(null);
    setSlides([]);
    try {
      const result = await generatePresentationContent(topic);
      setSlides(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An unknown error occurred.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (downloadMenuRef.current && !downloadMenuRef.current.contains(event.target as Node)) {
        setIsDownloadMenuOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  const generateFileContent = (format: 'txt' | 'md' | 'json'): { content: string; mimeType: string; extension: string } => {
    if (!slides.length) return { content: '', mimeType: '', extension: '' };

    const title = `Presentation Outline: ${topic}`;

    switch (format) {
      case 'json':
        return {
          content: JSON.stringify({ title, slides }, null, 2),
          mimeType: 'application/json;charset=utf-8',
          extension: 'json',
        };
      case 'md':
        const mdContent = `# ${title}\n\n${slides.map((slide, index) => `## Slide ${index + 1}: ${slide.title}\n\n${slide.content.map(point => `- ${point}`).join('\n')}`).join('\n\n')}`;
        return {
          content: mdContent,
          mimeType: 'text/markdown;charset=utf-8',
          extension: 'md',
        };
      case 'txt':
      default:
        const txtContent = `${title}\n\n${slides.map((slide, index) => `Slide ${index + 1}: ${slide.title}\n${slide.content.map(point => `  - ${point}`).join('\n')}`).join('\n\n')}`;
        return {
          content: txtContent,
          mimeType: 'text/plain;charset=utf-8',
          extension: 'txt',
        };
    }
  };

  const handleDownload = async (format: 'txt' | 'md' | 'json' | 'pptx' | 'pdf') => {
    setIsDownloadMenuOpen(false);
    
    if (format === 'pptx') {
        if (typeof PptxGenJS === 'undefined') {
            setError("PPTX generation library is not loaded. Please check your internet connection and try again.");
            return;
        }
        const pptx = new PptxGenJS();
        pptx.layout = 'LAYOUT_WIDE';

        // Title Slide
        const titleSlide = pptx.addSlide();
        titleSlide.addText(topic, { x: 0.5, y: 2.0, w: '90%', h: 1, align: 'center', fontSize: 44, color: '0088CC', bold: true });
        titleSlide.addText('Generated by Prism AI', { x: 0.5, y: 3.5, w: '90%', h: 0.75, align: 'center', fontSize: 18, color: '666666' });

        // Content Slides
        slides.forEach(slideData => {
            const slide = pptx.addSlide();
            slide.addText(slideData.title, { x: 0.5, y: 0.25, w: '90%', h: 0.75, fontSize: 32, bold: true, color: '0088CC' });
            if(slideData.content.length > 0) {
                 slide.addText(
                    slideData.content.map(point => ({ text: point, options: { bullet: true, indentLevel: 0, fontSize: 20, paraSpaceAfter: 10 } })),
                    { x: 0.5, y: 1.25, w: '90%', h: 5 }
                );
            }
        });

        await pptx.writeFile({ fileName: `presentation_${topic.slice(0, 20).replace(/\s/g, '_')}.pptx` });
        return;
    }

    if (format === 'pdf') {
        if (typeof jspdf === 'undefined') {
            setError("PDF generation library is not loaded. Please check your internet connection and try again.");
            return;
        }
        const { jsPDF } = jspdf;
        const doc = new jsPDF();
        const pageHeight = doc.internal.pageSize.height;
        const pageWidth = doc.internal.pageSize.width;
        const margin = 15;
        let y = margin;

        // Title
        doc.setFontSize(24);
        doc.setFont(undefined, 'bold');
        doc.text(topic, pageWidth / 2, y, { align: 'center' });
        y += 20;

        slides.forEach((slideData, index) => {
            const slideTitle = `Slide ${index + 1}: ${slideData.title}`;
            
            // Check for new page for the slide title
            if (y + 10 > pageHeight - margin) {
                doc.addPage();
                y = margin;
            }

            doc.setFontSize(18);
            doc.setFont(undefined, 'bold');
            doc.text(slideTitle, margin, y);
            y += 10;

            doc.setFontSize(12);
            doc.setFont(undefined, 'normal');
            slideData.content.forEach(point => {
                const textLines = doc.splitTextToSize(`• ${point}`, pageWidth - (margin * 2) - 5);
                const textHeight = textLines.length * (12 * 0.35);

                if (y + textHeight > pageHeight - margin) {
                    doc.addPage();
                    y = margin;
                }
                
                doc.text(textLines, margin + 5, y);
                y += textHeight + 3;
            });
            y += 10;
        });

        doc.save(`presentation_${topic.slice(0, 20).replace(/\s/g, '_')}.pdf`);
        return;
    }
    
    const { content, mimeType, extension } = generateFileContent(format);
    if (!content) return;
    
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `presentation_${topic.slice(0, 20).replace(/\s/g, '_')}.${extension}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Presentation Content Generator">
      <div className="p-6">
        <p className="text-sm text-gray-400 mb-4">
          Provide a topic, and the AI will generate a structured, slide-by-slide outline for your presentation.
        </p>
        <form onSubmit={handleSubmit} className="flex items-center space-x-2 mb-6">
          <input
            type="text"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., The Future of AI..."
            className="w-full bg-gray-700 border border-gray-600 rounded-md py-2 px-4 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500"
            disabled={isLoading}
          />
          <button
            type="submit"
            disabled={isLoading || !topic.trim()}
            className="bg-cyan-500 text-white rounded-md px-4 py-2 hover:bg-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2 focus:ring-offset-gray-800 transition duration-300 disabled:bg-gray-600 disabled:cursor-not-allowed flex-shrink-0"
          >
            {isLoading ? <Loader /> : 'Generate'}
          </button>
        </form>

        {error && <p className="text-center text-red-400 bg-red-900/50 p-3 rounded-lg">{error}</p>}
        
        {slides.length > 0 && (
          <div>
            <div className="space-y-4 max-h-[50vh] overflow-y-auto pr-2">
              <h3 className="text-lg font-semibold text-cyan-400">Presentation Outline: {topic}</h3>
              {slides.map((slide, index) => (
                <div key={index} className="bg-gray-900/50 p-4 rounded-lg border border-gray-700">
                  <h4 className="font-bold text-white text-md">Slide {index + 1}: {slide.title}</h4>
                  <ul className="list-disc list-inside mt-2 space-y-1 text-gray-300 text-sm">
                    {slide.content.map((point, pointIndex) => (
                      <li key={pointIndex}>{point}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
            <div className="relative mt-6">
              <button
                onClick={() => setIsDownloadMenuOpen(prev => !prev)}
                className="w-full text-sm bg-gray-700 text-cyan-300 border border-gray-600 px-4 py-2 rounded-md hover:bg-gray-600 transition-colors duration-200 flex items-center justify-center space-x-2"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                <span>Download Outline</span>
              </button>
              {isDownloadMenuOpen && (
                <div ref={downloadMenuRef} className="absolute bottom-full mb-2 w-full bg-gray-600 border border-gray-500 rounded-md shadow-lg z-10">
                  <button onClick={() => handleDownload('pptx')} className="w-full text-left px-4 py-2 text-sm text-gray-200 hover:bg-gray-500 transition-colors rounded-t-md flex items-center space-x-2">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                    <span>As PowerPoint (.pptx)</span>
                  </button>
                  <button onClick={() => handleDownload('pdf')} className="w-full text-left px-4 py-2 text-sm text-gray-200 hover:bg-gray-500 transition-colors flex items-center space-x-2">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                    <span>As PDF (.pdf)</span>
                  </button>
                  <hr className="border-gray-500"/>
                  <button onClick={() => handleDownload('txt')} className="w-full text-left px-4 py-2 text-sm text-gray-200 hover:bg-gray-500 transition-colors flex items-center space-x-2"><span>As Plain Text (.txt)</span></button>
                  <button onClick={() => handleDownload('md')} className="w-full text-left px-4 py-2 text-sm text-gray-200 hover:bg-gray-500 transition-colors flex items-center space-x-2"><span>As Markdown (.md)</span></button>
                  <button onClick={() => handleDownload('json')} className="w-full text-left px-4 py-2 text-sm text-gray-200 hover:bg-gray-500 transition-colors rounded-b-md flex items-center space-x-2"><span>As JSON (.json)</span></button>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </Modal>
  );
};

export default PresentationGenerator;